# Generated by Django 5.2.9 on 2025-12-22 04:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('base_price_usd', models.DecimalField(decimal_places=2, help_text='Precio en dólares estadounidenses', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Base USD')),
                ('base_price_cop', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en pesos colombianos (opcional, se calcula automáticamente si no se provee)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Base COP')),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='IVA aplicable en Colombia (default 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje IVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(choices=[('USD', 'US Dollar'), ('COP', 'Colombian Peso')], default='USD', max_length=3, verbose_name='Moneda Origen')),
                ('to_currency', models.CharField(choices=[('USD', 'US Dollar'), ('COP', 'Colombian Peso')], default='COP', max_length=3, verbose_name='Moneda Destino')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Cuántas unidades de la moneda destino por 1 unidad de origen', max_digits=10, verbose_name='Tasa de Cambio')),
                ('source', models.CharField(default='Manual', help_text='API o fuente de donde se obtuvo la tasa (ej: OpenExchangeRates, Manual)', max_length=100, verbose_name='Fuente')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-effective_date'], name='payments_ex_from_cu_7642e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Orden')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('COP', 'Colombian Peso')], max_length=3, verbose_name='Moneda')),
                ('payment_gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('BOLD', 'Bold'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=20, verbose_name='Pasarela de Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Monto antes de impuestos', max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de impuestos aplicados (principalmente para COP)', max_digits=12, verbose_name='Impuestos (IVA)')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total a pagar (subtotal + impuestos)', max_digits=12, verbose_name='Total')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa USD->COP utilizada en el momento de la orden', max_digits=10, null=True, verbose_name='Tasa de Cambio')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PROCESSING', 'Procesando Pago'), ('PAID', 'Pagado'), ('FAILED', 'Pago Fallido'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención aplicable en Colombia', max_digits=12, verbose_name='Retención en la Fuente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='ID de transacción provisto por Stripe, Bold, o Mercado Pago', max_length=255, unique=True, verbose_name='ID Externo')),
                ('payment_intent_id', models.CharField(blank=True, help_text='ID del intent de pago (específico de Stripe)', max_length=255, null=True, verbose_name='Payment Intent ID')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Pago'), ('REFUND', 'Reembolso'), ('PARTIAL_REFUND', 'Reembolso Parcial')], default='PAYMENT', max_length=20, verbose_name='Tipo de Transacción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SUCCESS', 'Exitosa'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada'), ('REFUNDED', 'Reembolsada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('COP', 'Colombian Peso')], max_length=3, verbose_name='Moneda')),
                ('payment_gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('BOLD', 'Bold'), ('MERCADO_PAGO', 'Mercado Pago')], max_length=20, verbose_name='Pasarela de Pago')),
                ('webhook_payload', models.JSONField(blank=True, help_text='Datos completos recibidos del webhook para auditoría', null=True, verbose_name='Payload del Webhook')),
                ('gateway_response', models.JSONField(blank=True, help_text='Respuesta original de la API de la pasarela', null=True, verbose_name='Respuesta de la Pasarela')),
                ('error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Error')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Reembolsado')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Razón del Reembolso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='payments_or_order_n_80ab42_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='payments_or_user_id_064188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='payments_or_status_daab12_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id'], name='payments_tr_externa_bdcbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', '-created_at'], name='payments_tr_order_i_62eea4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_gateway', 'status'], name='payments_tr_payment_98004c_idx'),
        ),
    ]
